/*
=====================================================================================
Project: Exploritory Data Analysis in SQL
===================================================================================
PURPOSE:

SOURCE:
Data with Baraa

*/

-- ==============================================================================
-- Database exploration 
-- ===============================================================================

-- Explore all objects in the the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dim_customers'

-- ===================================================================================
-- Dimention Exploration 
-- ====================================================================================

-- Explore 
SELECT DISTINCT country FROM gold.dim_customers

-- Explore all categories and subcategories
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3

SELECT DB_NAME() AS current_db;


-- ===================================================================================
-- Date Exploration
-- ====================================================================================

-- Find the date of the first and last order
SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date, 
	DATEDIFF (year, MIN(order_date),MAX(order_date)) AS order_range_years
FROM gold.fact_sales

-- Find the youngest and the olders customer 
SELECT 
	MIN(birthdate) AS oldest_birthdate,
	DATEDIFF (year, MIN(birthdate), GETDATE()) AS oldest_age,
	MAX(birthdate) AS youngest_birthdate,
	DATEDIFF (year, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers

-- ================================================================================================
-- Measure Exploration
-- ==================================================================================

-- Find the total sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) AS total_quantity FROM gold.fact_sales

-- Find the total number of orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_order FROM gold.fact_sales
SELECT * FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(product_name) AS total_products FROM gold.dim_products
SELECT COUNT(DISTINCT product_name) AS total_products FROM gold.dim_products
SELECT COUNT(product_key) AS total_product FROM gold.dim_products

-- Find the total number of customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales

-- Generate the report
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS total_sales FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS total_sales FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS total_quantity FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr Orders' AS measure_name, COUNT(order_number) AS total_orders FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr Products' AS measure_name, COUNT(product_name) AS total_products FROM gold.dim_products
UNION ALL
SELECT 'Total Nr Customer' AS meause_name, COUNT(customer_key) AS total_customers FROM gold.dim_customers

-- =========================================================================================
-- Magnitude
-- =========================================================================================

-- Find total customers by countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by categories
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT 
category, 
AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;

-- What is the total revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON p.product_key=f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Find total revenue is generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key=f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC


-- What is the distibutions of sold items across countries?

SELECT c.country, 
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key=f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC

-- =====================================================================================
-- Ranking
-- =====================================================================================

-- Which 5 products generate the highest revenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- 2nd method
SELECT *
FROM(
	SELECT 
	p.product_name,
	SUM(f.sales_amount) total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC)AS rank_products
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key=f.product_key
	GROUP BY p.product_name
	ORDER BY total_revenue DESC) t
WHERE rank_products <= 5


-- What are the 5 worst-performing products in terms of sales?

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY p.product_name
ORDER BY total_revenue 
